This notebook uses codes developed by Kylie Huch to save synapse count dataset from connectome.

In [1]:
# pd.set_option("display.max_rows", None)

import os
from pathlib import Path
import re
import math
import itertools
import importlib

import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import seaborn as sns

import bokeh
import bokeh.palettes
from bokeh.plotting import figure
from bokeh.io import output_notebook, show as bokeh_show

import holoviews as hv
import hvplot.pandas

import neuprint
from neuprint import SynapseCriteria

from scipy.optimize import curve_fit, least_squares

# import 2 libaries.
# Add library folder to Python path
import sys
project_root = Path.cwd().parent
library_path = project_root / "library"

if str(library_path) not in sys.path:
    sys.path.append(str(library_path))

import kylie_lib as cl
from kylie_lib import syn_specs

import lib_compare_receptor_to_neuprint_synapses as connectome

import lib_glucl_drive as glucl

output_notebook(hide_banner=True)
show = bokeh_show

notes:
1. primary_roi = False if want to look at substructure synapses (non primary), otherwise the synapses will be fetched twice.
2. if look at primary roi (PB, EB),  = true
3. When discrepancy between neuprint output and code output: there are non-labelled synapses in neuprint; this d7 might not arborizing to thie L9 (check using visualization!);truncated neuron (Status: not traced)...
4. website: https://connectome-neuprint.github.io/neuprint-python/docs/queries.html
5. I checked with neuprint: Kylie's visualization is anterior top (facing me), BUT neuprint's labelling of L and R is posterior top (so consistent with my confocal/airyscan imaging). So a L5R4_L in this visualization has cell body (and the L5) on the right, BUT in neuprint, if look from posterior, cell body and the L5 are on the left.
6. "pre" and "post": This is from the point of view of the target neuron. So, "pre" to the target neuron means looking for the upstream neurons inputing to this target neuron!
7. why would .fetch_syn_conns() and .skeleton_synapse_visualization() gives different total synapse number: the latter excludes synapses from/to neurons with type_post=NaN, while the former keeps everything. The number obtained using the latter should be smaller than the former, and neuprint number actually equals the latter (because the post_type needs to be identifiable)!


8. **male-cns:v0.9: WARNING!!! This dataset doesn't have glomerulus ROI define inside PB!!! So I can't do the same analysing with this new dataset yet...**

In [2]:
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGllaHVjaEBiZXJrZWxleS5lZHUiLCJsZXZlbCI6Im5vYXV0aCIsImltYWdlLXVybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0tpVkJGeHFzT1JxRlhnNnNOX0xIWnd4RjRoWDJORWh4WFBpY2hDaEV1Qjdsei0yUT1zOTYtYz9zej01MD9zej01MCIsImV4cCI6MTkyMjI1NDAyMH0.WLushXPCMuxMHltv_LUpoVmhtGyZSTZw08ShIrEboLY"

c = neuprint.Client('neuprint.janelia.org', 'hemibrain:v1.2.1', TOKEN)
#c = neuprint.Client('neuprint.janelia.org', 'male-cns:v0.9', TOKEN)

# need to change to 'male-cns:v0.9' if want to use another dataset because neuprint only uses one active client at a time.

In [3]:
results_dir = project_root / "results" / "connectome"
results_dir.mkdir(parents=True, exist_ok=True)

hemibrain_d7_names = pd.read_csv(results_dir / "hemibrainv121_d7_names.csv")
male_d7_names = pd.read_csv(results_dir / "malev09_d7_names.csv")

<font size="10">PART ZERO</font>

This section obtains the synapse count from neuprint. Specifically, it gets all Delta7 input to each Delta7 at each glomerulus, as well as all LPsP, all P1-9, and all P6-8P9 input.

In [4]:
'''This cell downloads the synapse count from connectome. Should be used only once per dataset.'''
conn_id = "Delta7"        # <-- change here do get input from another cell
'''
"LPsP"    15min
"P1-9"    13min   # WARNING! I don't know the name for P1-9 in male-cns...and the one suggested automatically seems wrong...
"Delta7"  22min
"P6-8P9"  7min
seems like the names of the same neurons are different across datasets!!!
'''
dataset_name = "hemibrainv1.2.1"    # change to malev0.9 if needed.
#dataset_name = "malev0.9"

output_dir = results_dir / dataset_name / conn_id

all_d7_upstream_results = connectome.fetch_d7_upstream_by_glomerulus(
    d7_names_df=hemibrain_d7_names,     # <-- change here
    output_dir=output_dir,
    conn_id=conn_id
)

print(f"Saved {len(all_d7_upstream_results)} files into: {output_dir}")

AssertionError: Unrecognized synapse rois: {'PB(R1)'}

In [24]:
from neuprint import fetch_all_rois
rois = fetch_all_rois(client=c)
for i, roi in enumerate(rois):
    print(i, roi)

0 AB(L)
1 AB(R)
2 AL(L)
3 AL(R)
4 AL-D(L)
5 AL-D(R)
6 AL-DA1(R)
7 AL-DA2(L)
8 AL-DA2(R)
9 AL-DA3(L)
10 AL-DA3(R)
11 AL-DA4l(R)
12 AL-DA4m(L)
13 AL-DA4m(R)
14 AL-DC1(L)
15 AL-DC1(R)
16 AL-DC2(L)
17 AL-DC2(R)
18 AL-DC3
19 AL-DC3(R)
20 AL-DC4(L)
21 AL-DC4(R)
22 AL-DL1(R)
23 AL-DL2d(R)
24 AL-DL2v(R)
25 AL-DL3(R)
26 AL-DL4(L)
27 AL-DL4(R)
28 AL-DL5(L)
29 AL-DL5(R)
30 AL-DM1(L)
31 AL-DM1(R)
32 AL-DM2(L)
33 AL-DM2(R)
34 AL-DM3(L)
35 AL-DM3(R)
36 AL-DM4(L)
37 AL-DM4(R)
38 AL-DM5(L)
39 AL-DM5(R)
40 AL-DM6(L)
41 AL-DM6(R)
42 AL-DP1l(R)
43 AL-DP1m(L)
44 AL-DP1m(R)
45 AL-V(R)
46 AL-VA1d(R)
47 AL-VA1v(R)
48 AL-VA2(R)
49 AL-VA3(R)
50 AL-VA4(R)
51 AL-VA5(R)
52 AL-VA6(L)
53 AL-VA6(R)
54 AL-VA7l(R)
55 AL-VA7m(R)
56 AL-VC1(R)
57 AL-VC2(R)
58 AL-VC3l(R)
59 AL-VC3m(R)
60 AL-VC4(R)
61 AL-VC5(R)
62 AL-VL1(R)
63 AL-VL2a(R)
64 AL-VL2p(R)
65 AL-VM1(R)
66 AL-VM2(R)
67 AL-VM3(R)
68 AL-VM4(R)
69 AL-VM5d(R)
70 AL-VM5v(R)
71 AL-VM7d(L)
72 AL-VM7d(R)
73 AL-VM7v(L)
74 AL-VM7v(R)
75 AL-VP1d(R)
76 AL-VP1l(R)
77 AL-VP1m(R)
78 AL-VP2(R)
79 AL-VP3(R)
80 AL-VP4(R)
81 AL-VP5(R)
82 AME(R)
83 AMMC
84 AOT(R)
85 AOTU(R)
86 ATL(L)
87 ATL(R)
88 AVLP(R)
89 BU(L)
90 BU(R)
91 CA(L)
92 CA(R)
93 CAN(R)
94 CRE(-ROB,-RUB)(R)
95 CRE(-RUB)(L)
96 CRE(L)
97 CRE(R)
98 CX
99 EB
100 EBr1
101 EBr2r4
102 EBr3am
103 EBr3d
104 EBr3pw
105 EBr5
106 EBr6
107 EPA(L)
108 EPA(R)
109 FB
110 FB-column3
111 FBl1
112 FBl2
113 FBl3
114 FBl4
115 FBl5
116 FBl6
117 FBl7
118 FBl8
119 FBl9
120 FLA(R)
121 GA(R)
122 GC
123 GF(R)
124 GNG
125 GOR(L)
126 GOR(R)
127 IB
128 ICL(L)
129 ICL(R)
130 INP
131 IPS(R)
132 LAL(-GA)(R)
133 LAL(L)
134 LAL(R)
135 LH(R)
136 LO(R)
137 LOP(R)
138 LX(L)
139 LX(R)
140 MB(+ACA)(R)
141 MB(L)
142 MB(R)
143 ME(R)
144 NO
145 NO(L)
146 NO(R)
147 NO1(L)
148 NO1(R)
149 NO2(L)
150 NO2(R)
151 NO3(L)
152 NO3(R)
153 OL(R)
154 PB
155 PB(L1)
156 PB(L2)
157 PB(L3)
158 PB(L4)
159 PB(L5)
160 PB(L6)
161 PB(L7)
162 PB(L8)
163 PB(L9)
164 PB(R1)
165 PB(R2)
166 PB(R3)
167 PB(R4)
168 PB(R5)
169 PB(R6)
170 PB(R7)
171 PB(R8)
172 PB(R9)
173 PED(R)
174 PENP
175 PLP(R)
176 POC
177 PRW
178 PVLP(R)
179 ROB(R)
180 RUB(L)
181 RUB(R)
182 SAD
183 SAD(-AMMC)
184 SCL(L)
185 SCL(R)
186 SIP(L)
187 SIP(R)
188 SLP(R)
189 SMP(L)
190 SMP(R)
191 SNP(L)
192 SNP(R)
193 SPS(L)
194 SPS(R)
195 VES(L)
196 VES(R)
197 VLNP(R)
198 VMNP
199 WED(R)
200 a'1(R)
201 a'2(R)
202 a'3(R)
203 a'L(L)
204 a'L(R)
205 a1(R)
206 a2(R)
207 a3(R)
208 aL(L)
209 aL(R)
210 b'1(R)
211 b'2(R)
212 b'L(L)
213 b'L(R)
214 b1(R)
215 b2(R)
216 bL(L)
217 bL(R)
218 dACA(R)
219 g1(R)
220 g2(R)
221 g3(R)
222 g4(R)
223 g5(R)
224 gL(L)
225 gL(R)
226 hemibrain
227 lACA(R)
228 mALT(L)
229 mALT(R)
230 vACA(R)

In [25]:
[r for r in rois if "PB" in r]

['PB',
 'PB(L1)',
 'PB(L2)',
 'PB(L3)',
 'PB(L4)',
 'PB(L5)',
 'PB(L6)',
 'PB(L7)',
 'PB(L8)',
 'PB(L9)',
 'PB(R1)',
 'PB(R2)',
 'PB(R3)',
 'PB(R4)',
 'PB(R5)',
 'PB(R6)',
 'PB(R7)',
 'PB(R8)',
 'PB(R9)']

In [29]:
'''This cell downloads per-cell Delta7→Delta7 synapse counts in PB.
Each output CSV contains one row per presynaptic Delta7 neuron/bodyId.
'''

conn_id = "Delta7"

dataset_name = "hemibrainv1.2.1"
# dataset_name = "malev0.9"

output_dir = results_dir / dataset_name / "Delta7_per_cell"

all_d7_upstream_per_cell_results = glucl.fetch_d7_upstream_per_cell(
    d7_names_df=hemibrain_d7_names,   # change to male_d7_names if needed
    output_dir=output_dir,
    conn_id=conn_id,
    rois="PB",
    primary_only=True,
)

print(f"Saved {len(all_d7_upstream_per_cell_results)} files into: {output_dir}")

Fetching pre-synaptic connections...

  0%|          | 0/724 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/554 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/644 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/593 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/611 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/532 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/567 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/525 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/611 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/502 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/518 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/611 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/578 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/580 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/583 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/551 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/561 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/565 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/650 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/643 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/511 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/567 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/676 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/593 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/557 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/588 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/581 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/585 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/520 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/589 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/552 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/581 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/684 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/580 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/478 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/564 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/544 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/619 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/647 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/590 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/606 [00:00<?, ?it/s]

Fetching pre-synaptic connections...

  0%|          | 0/561 [00:00<?, ?it/s]

Saved 42 files into: /Users/fisherguest/Documents/Projects/connectome_analysis_fisherlab/send_to_fisherlabgithub/results/connectome/hemibrainv1.2.1/Delta7_per_cell

In [16]:
importlib.reload(connectome)

In [17]:
dataset_name = "hemibrainv1.2.1"

output_dir = results_dir / dataset_name / "all_cell_to_each_Delta7"

dict_d7_upstream_by_type = connectome.fetch_d7_upstream_by_neuron_type(
    d7_names_df=hemibrain_d7_names,
    output_dir=output_dir,
    rois="PB",
    include_nonprimary=False,
)

print(f"Saved {len(dict_d7_upstream_by_type)} files into: {output_dir}")

Fetching upstream types for Delta7 911911004 (L1L9R8_R)...
Fetching upstream types for Delta7 911919917 (L1L9R8_R)...
Fetching upstream types for Delta7 5813061383 (L1L9R8_R)...
Fetching upstream types for Delta7 911574261 (L1L9R8_R)...
Fetching upstream types for Delta7 881221166 (L1L9R8_R)...
Fetching upstream types for Delta7 911470352 (L2R7_R)...
Fetching upstream types for Delta7 911574041 (L2R7_R)...
Fetching upstream types for Delta7 942522378 (L2R7_R)...
Fetching upstream types for Delta7 911578496 (L2R7_R)...
Fetching upstream types for Delta7 911911699 (L2R7_R)...
Fetching upstream types for Delta7 911565419 (L3R6_R)...
Fetching upstream types for Delta7 941469087 (L3R6_R)...
Fetching upstream types for Delta7 910783961 (L3R6_R)...
Fetching upstream types for Delta7 911906936 (L3R6_R)...
Fetching upstream types for Delta7 910442723 (L4R5_R)...
Fetching upstream types for Delta7 911138168 (L4R5_R)...
Fetching upstream types for Delta7 911129339 (L4R5_R)...
Fetching upstream types for Delta7 911134009 (L4R5_R)...
Fetching upstream types for Delta7 880880259 (L4R5_R)...
Fetching upstream types for Delta7 911901802 (L4R6_R)...
Fetching upstream types for Delta7 910442782 (L4R6_R)...
Fetching upstream types for Delta7 910801332 (L5R4_L)...
Fetching upstream types for Delta7 910796989 (L5R4_L)...
Fetching upstream types for Delta7 880875736 (L5R4_L)...
Fetching upstream types for Delta7 880530613 (L5R4_L)...
Fetching upstream types for Delta7 5813048042 (L5R4_L)...
Fetching upstream types for Delta7 941482720 (L6R3_L)...
Fetching upstream types for Delta7 941814787 (L6R3_L)...
Fetching upstream types for Delta7 734581598 (L6R3_L)...
Fetching upstream types for Delta7 911919044 (L6R3_L)...
Fetching upstream types for Delta7 973959177 (L6R3_L)...
Fetching upstream types for Delta7 911211196 (L6R4_L)...
Fetching upstream types for Delta7 911241750 (L6R4_L)...
Fetching upstream types for Delta7 911129204 (L7R2_L)...
Fetching upstream types for Delta7 912243353 (L7R2_L)...
Fetching upstream types for Delta7 1158747783 (L7R2_L)...
Fetching upstream types for Delta7 941810314 (L7R3_L)...
Fetching upstream types for Delta7 911578595 (L8R1R9_L)...
Fetching upstream types for Delta7 910783883 (L8R1R9_L)...
Fetching upstream types for Delta7 910783731 (L8R1R9_L)...
Fetching upstream types for Delta7 910442752 (L8R1R9_L)...
Fetching upstream types for Delta7 911911193 (L8R1R9_L)...
Saved 42 files into: /Users/fisherguest/Documents/Projects/connectome_analysis_fisherlab/send_to_fisherlabgithub/results/connectome/hemibrainv1.2.1/all_cell_to_each_Delta7

In [5]:
hemibrain_d7_names.head()

,id,instance,type,status,inputs (#post),outputs (#pre),#voxels
0,911911004,L1L9R8_R,Delta7,Traced,1496,653,1405984537
1,911919917,L1L9R8_R,Delta7,Traced,1182,562,1330959441
2,5813061383,L1L9R8_R,Delta7,Traced,1322,608,1252686779
3,911574261,L1L9R8_R,Delta7,Traced,1283,579,1331108352
4,881221166,L1L9R8_R,Delta7,Traced,1285,606,1392031704

In [6]:
from kylie_lib import fetch_connectivity

In [18]:
all_results = {}
neuron_id=734581598
conn_df = fetch_connectivity(
            target_scale="neuron",
            conn_scale="all",
            conn_type="pre",
            target_id=neuron_id,
            conn_id=None,
            rois='PB',
            include_nonprimary=False,
        )
conn_df

,bodyId_pre,instance_pre,type_pre,bodyId_post,instance_post,type_post,roi,weight
22,758419409,EPG(PB08)_L3,EPG,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,28
36,910442782,Delta7(PB15)_L4R6_R,Delta7,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,22
62,911919044,Delta7(PB15)_L6R3_L,Delta7,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,22
7,572870540,EPG(PB08)_L1,EPG,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,22
115,1447576662,EPG(PB08)_L1,EPG,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,22
...,...,...,...,...,...,...,...,...
88,1003672833,IbSpsP(PB17)_L6/7,IbSpsP,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,1
16,666312288,PFR_b(PB11b)_L1_C2,PFR_b,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,1
85,973963898,IbSpsP(PB17)_L3/4,IbSpsP,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,1
80,942959557,IbSpsP(PB17)_L6/7,IbSpsP,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,1
91,1035640810,IbSpsP(PB17)_R2/3,IbSpsP,734581598,Delta7(PB15)_L6R3_L,Delta7,PB,1

In [19]:
summary_df = (
                conn_df
                .groupby("type_pre", dropna=False)
                .agg(
                    synapse_count=("weight", "sum"),
                    n_upstream_cells=("bodyId_pre", "nunique"),
                )
                .reset_index()
                .rename(columns={"type_pre": "upstream_type"})
                .sort_values("synapse_count", ascending=False)
                .reset_index(drop=True)
            )

In [20]:
summary_df.insert(0, "target_instance", 'L1L9R8_R')
summary_df.insert(0, "target_id", neuron_id)

In [21]:
summary_df

    target_id target_instance upstream_type  synapse_count  n_upstream_cells
0   734581598        L1L9R8_R        Delta7            520                41
1   734581598        L1L9R8_R           EPG            376                42
2   734581598        L1L9R8_R          LPsP             20                 2
3   734581598        L1L9R8_R        IbSpsP             19                13
4   734581598        L1L9R8_R          P1-9             13                 2
5   734581598        L1L9R8_R          PFNv             12                 7
6   734581598        L1L9R8_R         PFR_b             12                 6
7   734581598        L1L9R8_R          EPGt              6                 1
8   734581598        L1L9R8_R          PFGs              6                 5
9   734581598        L1L9R8_R          SpsP              4                 2
10  734581598        L1L9R8_R           NaN              4                 2
11  734581598        L1L9R8_R          PFNa              2                 2
12  734581598        L1L9R8_R   PEN_b(PEN2)              1                 1
13  734581598        L1L9R8_R          PFL1              1                 1
14  734581598        L1L9R8_R          PFL2              1                 1
15  734581598        L1L9R8_R          SIFa              1                 1